config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #resources :users
  resources :posts
  get 'posts/page/(:page(.:format))', to: 'posts#index'
  get 'aboutus', to: 'home#aboutus'
  get 'home(/:hello)', to: 'home#index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :commentable, polymorphic: true
  validates_associated :user
  validates :body, length: { maximum: 1000 }
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user # Автор
  has_many :comments, as: :commentable # Комментарии к сообщению
  has_many :commentators, through: :comments, source: :user
  validates_associated :user
  validates :body, length: { maximum: 10000, minimum: 50 }
  validates :title, length: { maximum: 100, minimum: 2 }
  validates :title, :body, presence: true
  validates :title, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :recoverable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :commented_posts, through: :comments, source: :commentable, source_type: :Post
  has_many :commented_users, through: :comments, source: :commentable, source_type: :User

  validates :name, :email, presence: true
  validates :name, length: { maximum: 16, minimum: 2 }
  validates :name, :email, uniqueness: true

  before_destroy :log_before_destory
  after_destroy :log_after_destory

  def log_before_destory
    Rails.logger.info '#########################################'
    Rails.logger.info "Перед удалением пользователя #{@name}"
    Rails.logger.info '#########################################'
  end

  def log_after_destory
    Rails.logger.info '#########################################'
    Rails.logger.info "После удаления пользователя #{@name}"
    Rails.logger.info '#########################################'
  end
  
	validates :name, presence: true
	validates :name, length: { maximum: 16, minimum: 2 }
	validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:times_here] ||= 0
    session[:times_here] += 1
    Rails.logger.info '#########################################'
    Rails.logger.info params.inspect
    Rails.logger.info params[:hello]
    Rails.logger.info '#########################################'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json

  def index
    @posts = Post.includes(:user).page(params[:page]).per(4)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.page(params[:page]).per(2)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :disactive)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/aboutus.html.slim
h1 Идущие на курс приветствуют тебя!
p Да улыбнётся нам Фортуна!
p
  = image_tag('aboutus.jpg')
p
= link_to 'Уйти отсель', root_path

app/views/home/footer.html.slim
h1 Home#footer
p Find me in app/views/home/footer.html.slim

app/views/home/index.html.slim
h1 Домашняя страница
p Когда-нибудь ты всё поймешь!
= link_to 'О нас', aboutus_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Blog Hello World
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    = render 'shared/header'
    = yield

#требования гема Devise
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/posts/show.html.slim
p#notice = notice

p
  strong Title:
  = @post.title
p
  strong Body:
  = @post.body
p
  strong User:
  = @post.user.name
p
  strong Disactive:
  = @post.disactive

table
  - @comments.order(created_at: :desc).each do |comment|
    tr
      td
        b = comment.user.name
      td = comment.body

= paginate @comments

=> link_to 'Edit', edit_post_path(@post)
'|
=< link_to 'Back', posts_path

app/views/shared/_footer.html.slim
p Это футер
p Copyright 2018 Школа лучших рубистов на свете

app/views/shared/_header.html.slim
header
  ul
    -if user_signed_in?
      li
        span Hello, #{current_user.email}
      li
        = link_to 'Log out', destroy_user_session_path, method: :delete
    -else
      li
        = link_to 'Log in', new_user_session_path
      li
        = link_to 'Register', new_user_registration_path